name: LateX Build
on:
  push:
    branches: [ main ]
    tags:
      - '**'
  workflow_dispatch:
jobs:
  BuildLatexJob:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git repo
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          pre_compile: "tlmgr update --self --all"
          args: "-pdf -jobname=main -file-line-error -halt-on-error -interaction=nonstopmode -logfilewarninglist -Werror "
          post_compile: "latexmk -c"
      - name: Split log
        if: failure()
        shell: bash
        run: cat main.log | grep -n -E 'LaTeX Error|LaTeX Warning|Undefined' > small.log
      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: Logs
          path: |
            main.log
            small.log 
      - name: Print small log
        if: failure()
        shell: bash
        run: cat small.log >&2
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            main.pdf
          
  TelegramFailureBuildJob:
      needs: [BuildLatexJob] #when finished this job
      if: failure() # if its failed
      runs-on: ubuntu-latest
      steps:
      - name: Clone Repo with Checkout 
        uses: actions/checkout@v2 # clones repo! Action implemented in this repository, tag "2"
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Logs
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
                ${{ github.event_name }} event,
                on github.com/${{ github.repository }}, 
                by ${{ github.actor }}:
                <b>${{ github.event.head_commit.message }}</b>
               ❌ <b>FAILED</b> ❌
          format: html
          disable_web_page_preview: true
          document: small.log
          
  TelegramSuccessBuildJob:
        needs: [BuildLatexJob] #when finished this job
        if: success() #only on success
        runs-on: ubuntu-latest
        steps:
        - name: Send custom Telegram message
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
                ${{ github.event_name }} event,
                on github.com/${{ github.repository }}, 
                by ${{ github.actor }}:
                <b>${{ github.event.head_commit.message }}</b>
                ✅ <b>SUCCEDED</b> ✅ 
            format: html
            disable_web_page_preview: true

  DeployJob:
    needs: BuildLatexJob
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo with Checkout 
        uses: actions/checkout@v2 
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Artifacts
      - name: Extract Date
        shell: bash
        id: extract_date
        run: |
          echo "::set-output name=DATE::Release-$(date +%F_%H-%M)"
      - name: Print Output Step
        run: echo ${{ steps.extract_date.outputs.DATE }}
      - name: Deploy
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"
          TAG="${{ steps.extract_date.outputs.DATE }}"
          MSG="${{ github.event.head_commit.message }}"
          echo $TAG
          hub release create -m "$TAG" "$TAG" || true #crea release 
          tree
          for f in ./*.pdf; do
            echo "Delivering file: $f"
            gh release upload "$TAG" "$f" --clobber
            rm $f
          done

  
  TelegramFailureDeployJob:
      needs: [DeployJob] #when finished this job
      if: failure() # if its failed
      runs-on: ubuntu-20.04
      steps:
      - name: Clone Repo with Checkout 
        uses: actions/checkout@v2 
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Logs
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              RELEASE
              ❌ <b>FAILED</b> ❌
          disable_web_page_preview: true
          document: small.log
          
  TelegramSuccessDeployJob:
      needs: [DeployJob] #when finished this job
      if: success() # if its ok
      runs-on: ubuntu-20.04
      steps:
      - name: Clone Repo with Checkout 
        uses: actions/checkout@v2 
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Artifacts
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              RELEASED!
              on https://github.com/ISIQuiz/ISIQuiz-Report/releases
          disable_web_page_preview: true
          document: main.pdf
          
          
  PandocConverterJob:
    needs: DeployJob
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v2
      - name: Setup git repo 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --all
      - name: Clone Pandoc dependency 
        run: |
          git clone https://github.com/SmartDogHouse/pandoc-uikit.git
      - name: Pandoc tex conversion
        uses: docker://pandoc/latex:latest
        with:
          args: >-
            -d ./pandoc-uikit/config.yaml 
            -o ./index.html 
            main.tex
            
      - name: Commit the new gh-pages html
        run: |
          git add ./index.html
          git commit -m "Invisible commit"
          rm -rdf pandoc-uikit/.git*
          git clean -fxd
          git checkout gh-pages
          git rm -rf .
          git clean -fxd
          git clone https://github.com/SmartDogHouse/pandoc-uikit.git
          rm -rdf pandoc-uikit/.git*
          #get the folders needed from the main branch
          git checkout main Extra
          git checkout main Images
          git checkout main index.html
          git status
          # git cherry-pick main, alternatives
          git add .
          git commit -m 'Updated gh-pages'
          git push

  TelegraFailurePandocConverterJob:
      needs: [PandocConverterJob] 
      if: failure()
      runs-on: ubuntu-20.04
      steps:
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              Website building 
              ❌ <b>FAILED</b> ❌
          disable_web_page_preview: true
          
  TelegramSuccessPandocConverterJob:
      needs: [PandocConverterJob] 
      if: success() 
      runs-on: ubuntu-20.04
      steps:
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              Website built! 
              ONLINE at https://isiquiz.github.io/ISIQuiz-Report//
          disable_web_page_preview: true
          