name: Meeting Reminder
on:
  schedule:
    - cron: "0 11 22 10 *" # Minutes-Hour(UTC Time!)-Day-Month
  workflow_dispatch:
jobs:
  BuildLatexJob:
    runs-on: ubuntu-latest
    steps:
      - name: Send curl message
        shell: bash
        run: curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d 'chat_id=${{ secrets.TELEGRAM_TO }}&text=Meeting Time!' 
